# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161002_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='druft',
            new_name='draft',
        ),
    ]
